// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nupqpsayufclflmtfjin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51cHFwc2F5dWZjbGZsbXRmamluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTU5OTksImV4cCI6MjA3MTMzMTk5OX0.TygJnNDGRpfDs0pqzoPtbjh3tf1jWYWrjhGtuY3hFr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});